name: Run Prettier Check
run-name: Running Prettier Check
on: [push]
jobs:
  Prettier-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run tests
        working-directory: ${{ github.workspace }}/client
        run: |
          npm run prettier-check
